using UnityEngine;

public class AttackZone : MonoBehaviour
{
    public int damage = 10;
    public float damageCooldown = 3f;
    private float lastDamageTime;

    void OnTriggerEnter2D(Collider2D other)
    {
        if (other.CompareTag("Player1")) // tag Þºng c?a b?n
        {
            if (Time.time - lastDamageTime > damageCooldown)
            {
                other.SendMessage("TakeDamage", damage, SendMessageOptions.DontRequireReceiver);
                lastDamageTime = Time.time;
                Debug.Log("?? Enemy ÞÃnh trºng player!");
            }
        }
    }

    void OnTriggerStay2D(Collider2D other)
    {
        if (other.CompareTag("Player1"))
        {
            if (Time.time - lastDamageTime > damageCooldown)
            {
                other.SendMessage("TakeDamage", damage, SendMessageOptions.DontRequireReceiver);
                lastDamageTime = Time.time;
                Debug.Log("?? Enemy liõn t?c gãy damage!");
            }
        }
    }
}
